
description: >- # this means to ignore newlines until "baseurl:"
  A Journal about tech stack solutions for the enterprise. Most recently,
  using Cloud-Native patterns, Big Data solutions and Open Source (OSS).
url: "" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: thelehhman/plainwhite-jekyll

# Theme Info: https://github.com/thelehhman/plainwhite-jekyll
theme: plainwhite

plainwhite:
  name: Alberto A. Flores
  tagline: Sr. Systems Architect
  date_format: "%b %-d, %Y"
  dark_mode: true
  search: true
  sitemap: true
  navigation:
    - title: Homework
      url: "/homework"
    - title: About me
      url: "/about"

  social_links:
    twitter: albertoaflores
    github: albertoaflores
    linkedIn: in/aflores\
    facebook: albertoaflores37
    youtube: albertoaflores
    rss: rss

#Enable excerpts in blog entries
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
