
description: >- # this means to ignore newlines until "baseurl:"
  A Journal about tech stack solutions for the enterprise. Most recently,
  using Cloud-Native patterns, Big Data solutions and Open Source (OSS).
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#remote_theme: albertoaflores/plainwhite-jekyll

# Theme Info: https://github.com/thelehhman/plainwhite-jekyll
#theme: plainwhite

plainwhite:
  name: Alberto A. Flores
  tagline: Sr. Systems Architect
  date_format: "%b %-d, %Y"
  dark_mode: true
  search: true
  sitemap: true
  #disqus_shortname: albertoaflores
  navigation:
    - title: Books
      url: "/books"
    - title: Homework
      url: "/homework"
    - title: About me
      url: "/about"

  social_links:
    twitter: albertoaflores
    github: albertoaflores
    linkedIn: in/aflores\
    facebook: albertoaflores37
    youtube: albertoaflores
    rss: rss

#Enable excerpts in blog entries
show_excerpts: true

markdown: kramdown

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

paginate: 10

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
